# Generated by Django 4.1.1 on 2022-09-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Категория")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории",},
        ),
        migrations.CreateModel(
            name="ProjectName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Наименование"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты",},
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Статус проекта"
                    ),
                ),
            ],
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты",},
        ),
        migrations.CreateModel(
            name="TextStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Характеристика"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Статус"),
                ),
                (
                    "project_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectname",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текстовая характеристика",
                "verbose_name_plural": "Текстовые характеристики",
            },
        ),
        migrations.CreateModel(
            name="BooleanStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=60, verbose_name="Характеристика"),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "projects_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectname",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bool-характеристика",
                "verbose_name_plural": "Bool-характеристики",
            },
        ),
    ]
