# Generated by Django 4.1.1 on 2022-09-30 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Категория")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории",},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Наименование"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_mental", models.BooleanField(verbose_name="Ментальная задача")),
                ("is_physical", models.BooleanField(verbose_name="Физическая задача")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Планируемый"),
                ),
                ("changed", models.DateTimeField(blank=True, verbose_name="Изменён")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты",},
        ),
        migrations.CreateModel(
            name="Subtask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=60, verbose_name="Характеристика"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "to_be_done_by_date",
                    models.DateField(blank=True, verbose_name="Сделаю к дате"),
                ),
                (
                    "to_be_done_in_time",
                    models.DateField(blank=True, verbose_name="Сделаю ко времени"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name=" Подзадача создана"
                    ),
                ),
            ],
            options={"verbose_name": "Подзадача", "verbose_name_plural": "Подзадачи",},
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=60, verbose_name="Характеристика"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "to_be_done_by_date",
                    models.DateField(blank=True, verbose_name="Сделаю к дате"),
                ),
                (
                    "to_be_done_in_time",
                    models.DateField(blank=True, verbose_name="Сделаю ко времени"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Задача создана"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи",},
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Заголовок"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                ("to_archive", models.BooleanField(verbose_name="Архивировать")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.task",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к задаче",
                "verbose_name_plural": "Комментарии к задаче",
            },
        ),
        migrations.CreateModel(
            name="SubtaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Заголовок"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                ("to_archive", models.BooleanField(verbose_name="Архивировать")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "subtask",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.subtask",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к подзадаче",
                "verbose_name_plural": "Комментарии к подзадаче",
            },
        ),
        migrations.AddField(
            model_name="subtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.task",
                verbose_name="Задача",
            ),
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Статус проекта"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Общий статус",
                "verbose_name_plural": "Общие статусы",
            },
        ),
        migrations.CreateModel(
            name="ProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Заголовок"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                ("to_archive", models.BooleanField(verbose_name="Архивировать")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к проекту",
                "verbose_name_plural": "Комментарии к проекту",
            },
        ),
    ]
