# Generated by Django 4.1.1 on 2022-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_changed_alter_project_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="to_be_done_by_date",
            field=models.DateField(blank=True, null=True, verbose_name="Сделаю к дате"),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="to_be_done_in_time",
            field=models.DateField(
                blank=True, null=True, verbose_name="Сделаю ко времени"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="to_be_done_by_date",
            field=models.DateField(blank=True, null=True, verbose_name="Сделаю к дате"),
        ),
        migrations.AlterField(
            model_name="task",
            name="to_be_done_in_time",
            field=models.DateField(
                blank=True, null=True, verbose_name="Сделаю ко времени"
            ),
        ),
    ]
